// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.KicUnit;

privileged aspect KicUnit_Roo_JavaBean {
    
    public String KicUnit.getName() {
        return this.name;
    }
    
    public void KicUnit.setName(String name) {
        this.name = name;
    }
    
}
