// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.Partner;
import javax.persistence.Entity;

privileged aspect Partner_Roo_Jpa_Entity {
    
    declare @type: Partner: @Entity;
    
}
