// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.TradeStyle;

privileged aspect TradeStyle_Roo_JavaBean {
    
    public String TradeStyle.getName() {
        return this.name;
    }
    
    public void TradeStyle.setName(String name) {
        this.name = name;
    }
    
}
