// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.Firm;
import com.innoenergy.kic2.domain.FirmDataOnDemand;
import com.innoenergy.kic2.domain.KicUnitDataOnDemand;
import com.innoenergy.kic2.domain.OrganizationTypeDataOnDemand;
import com.innoenergy.kic2.domain.TradeStyleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FirmDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FirmDataOnDemand: @Component;
    
    private Random FirmDataOnDemand.rnd = new SecureRandom();
    
    private List<Firm> FirmDataOnDemand.data;
    
    @Autowired
    private KicUnitDataOnDemand FirmDataOnDemand.kicUnitDataOnDemand;
    
    @Autowired
    private OrganizationTypeDataOnDemand FirmDataOnDemand.organizationTypeDataOnDemand;
    
    @Autowired
    private TradeStyleDataOnDemand FirmDataOnDemand.tradeStyleDataOnDemand;
    
    public Firm FirmDataOnDemand.getNewTransientFirm(int index) {
        Firm obj = new Firm();
        setComment(obj, index);
        setFullName(obj, index);
        setOfficialName(obj, index);
        setOfficialNameEnglish(obj, index);
        setShortName(obj, index);
        setVatNumber(obj, index);
        return obj;
    }
    
    public void FirmDataOnDemand.setComment(Firm obj, int index) {
        String comment = "comment_" + index;
        if (comment.length() > 500) {
            comment = comment.substring(0, 500);
        }
        obj.setComment(comment);
    }
    
    public void FirmDataOnDemand.setFullName(Firm obj, int index) {
        String fullName = "fullName_" + index;
        if (fullName.length() > 200) {
            fullName = fullName.substring(0, 200);
        }
        obj.setFullName(fullName);
    }
    
    public void FirmDataOnDemand.setOfficialName(Firm obj, int index) {
        String officialName = "officialName_" + index;
        if (officialName.length() > 200) {
            officialName = officialName.substring(0, 200);
        }
        obj.setOfficialName(officialName);
    }
    
    public void FirmDataOnDemand.setOfficialNameEnglish(Firm obj, int index) {
        String officialNameEnglish = "officialNameEnglish_" + index;
        if (officialNameEnglish.length() > 200) {
            officialNameEnglish = officialNameEnglish.substring(0, 200);
        }
        obj.setOfficialNameEnglish(officialNameEnglish);
    }
    
    public void FirmDataOnDemand.setShortName(Firm obj, int index) {
        String shortName = "shortName_" + index;
        if (shortName.length() > 100) {
            shortName = shortName.substring(0, 100);
        }
        obj.setShortName(shortName);
    }
    
    public void FirmDataOnDemand.setVatNumber(Firm obj, int index) {
        String vatNumber = "vatNumber_" + index;
        if (vatNumber.length() > 50) {
            vatNumber = vatNumber.substring(0, 50);
        }
        obj.setVatNumber(vatNumber);
    }
    
    public Firm FirmDataOnDemand.getSpecificFirm(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Firm obj = data.get(index);
        Long id = obj.getId();
        return Firm.findFirm(id);
    }
    
    public Firm FirmDataOnDemand.getRandomFirm() {
        init();
        Firm obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Firm.findFirm(id);
    }
    
    public boolean FirmDataOnDemand.modifyFirm(Firm obj) {
        return false;
    }
    
    public void FirmDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Firm.findFirmEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Firm' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Firm>();
        for (int i = 0; i < 10; i++) {
            Firm obj = getNewTransientFirm(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
