// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.Firm;
import com.innoenergy.kic2.domain.FirmDataOnDemand;
import com.innoenergy.kic2.domain.FirmIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FirmIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FirmIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FirmIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FirmIntegrationTest: @Transactional;
    
    @Autowired
    private FirmDataOnDemand FirmIntegrationTest.dod;
    
    @Test
    public void FirmIntegrationTest.testCountFirms() {
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", dod.getRandomFirm());
        long count = Firm.countFirms();
        Assert.assertTrue("Counter for 'Firm' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FirmIntegrationTest.testFindFirm() {
        Firm obj = dod.getRandomFirm();
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Firm' failed to provide an identifier", id);
        obj = Firm.findFirm(id);
        Assert.assertNotNull("Find method for 'Firm' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Firm' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FirmIntegrationTest.testFindAllFirms() {
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", dod.getRandomFirm());
        long count = Firm.countFirms();
        Assert.assertTrue("Too expensive to perform a find all test for 'Firm', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Firm> result = Firm.findAllFirms();
        Assert.assertNotNull("Find all method for 'Firm' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Firm' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FirmIntegrationTest.testFindFirmEntries() {
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", dod.getRandomFirm());
        long count = Firm.countFirms();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Firm> result = Firm.findFirmEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Firm' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Firm' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FirmIntegrationTest.testFlush() {
        Firm obj = dod.getRandomFirm();
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Firm' failed to provide an identifier", id);
        obj = Firm.findFirm(id);
        Assert.assertNotNull("Find method for 'Firm' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFirm(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Firm' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirmIntegrationTest.testMergeUpdate() {
        Firm obj = dod.getRandomFirm();
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Firm' failed to provide an identifier", id);
        obj = Firm.findFirm(id);
        boolean modified =  dod.modifyFirm(obj);
        Integer currentVersion = obj.getVersion();
        Firm merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Firm' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirmIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", dod.getRandomFirm());
        Firm obj = dod.getNewTransientFirm(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Firm' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Firm' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Firm' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FirmIntegrationTest.testRemove() {
        Firm obj = dod.getRandomFirm();
        Assert.assertNotNull("Data on demand for 'Firm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Firm' failed to provide an identifier", id);
        obj = Firm.findFirm(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Firm' with identifier '" + id + "'", Firm.findFirm(id));
    }
    
}
