// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.KicUnit;
import com.innoenergy.kic2.domain.KicUnitDataOnDemand;
import com.innoenergy.kic2.domain.KicUnitIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect KicUnitIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KicUnitIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KicUnitIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: KicUnitIntegrationTest: @Transactional;
    
    @Autowired
    private KicUnitDataOnDemand KicUnitIntegrationTest.dod;
    
    @Test
    public void KicUnitIntegrationTest.testCountKicUnits() {
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", dod.getRandomKicUnit());
        long count = KicUnit.countKicUnits();
        Assert.assertTrue("Counter for 'KicUnit' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KicUnitIntegrationTest.testFindKicUnit() {
        KicUnit obj = dod.getRandomKicUnit();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to provide an identifier", id);
        obj = KicUnit.findKicUnit(id);
        Assert.assertNotNull("Find method for 'KicUnit' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'KicUnit' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KicUnitIntegrationTest.testFindAllKicUnits() {
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", dod.getRandomKicUnit());
        long count = KicUnit.countKicUnits();
        Assert.assertTrue("Too expensive to perform a find all test for 'KicUnit', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<KicUnit> result = KicUnit.findAllKicUnits();
        Assert.assertNotNull("Find all method for 'KicUnit' illegally returned null", result);
        Assert.assertTrue("Find all method for 'KicUnit' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KicUnitIntegrationTest.testFindKicUnitEntries() {
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", dod.getRandomKicUnit());
        long count = KicUnit.countKicUnits();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<KicUnit> result = KicUnit.findKicUnitEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'KicUnit' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'KicUnit' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KicUnitIntegrationTest.testFlush() {
        KicUnit obj = dod.getRandomKicUnit();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to provide an identifier", id);
        obj = KicUnit.findKicUnit(id);
        Assert.assertNotNull("Find method for 'KicUnit' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKicUnit(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'KicUnit' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KicUnitIntegrationTest.testMergeUpdate() {
        KicUnit obj = dod.getRandomKicUnit();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to provide an identifier", id);
        obj = KicUnit.findKicUnit(id);
        boolean modified =  dod.modifyKicUnit(obj);
        Integer currentVersion = obj.getVersion();
        KicUnit merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'KicUnit' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KicUnitIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", dod.getRandomKicUnit());
        KicUnit obj = dod.getNewTransientKicUnit(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'KicUnit' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'KicUnit' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KicUnitIntegrationTest.testRemove() {
        KicUnit obj = dod.getRandomKicUnit();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KicUnit' failed to provide an identifier", id);
        obj = KicUnit.findKicUnit(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'KicUnit' with identifier '" + id + "'", KicUnit.findKicUnit(id));
    }
    
}
