// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.KicUnit;
import com.innoenergy.kic2.domain.KicUnitDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect KicUnitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: KicUnitDataOnDemand: @Component;
    
    private Random KicUnitDataOnDemand.rnd = new SecureRandom();
    
    private List<KicUnit> KicUnitDataOnDemand.data;
    
    public KicUnit KicUnitDataOnDemand.getNewTransientKicUnit(int index) {
        KicUnit obj = new KicUnit();
        setName(obj, index);
        return obj;
    }
    
    public void KicUnitDataOnDemand.setName(KicUnit obj, int index) {
        String name = "name_" + index;
        if (name.length() > 200) {
            name = name.substring(0, 200);
        }
        obj.setName(name);
    }
    
    public KicUnit KicUnitDataOnDemand.getSpecificKicUnit(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        KicUnit obj = data.get(index);
        Long id = obj.getId();
        return KicUnit.findKicUnit(id);
    }
    
    public KicUnit KicUnitDataOnDemand.getRandomKicUnit() {
        init();
        KicUnit obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return KicUnit.findKicUnit(id);
    }
    
    public boolean KicUnitDataOnDemand.modifyKicUnit(KicUnit obj) {
        return false;
    }
    
    public void KicUnitDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = KicUnit.findKicUnitEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'KicUnit' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<KicUnit>();
        for (int i = 0; i < 10; i++) {
            KicUnit obj = getNewTransientKicUnit(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
