// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.KicUnitDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect KicUnitDataOnDemand_Roo_Configurable {
    
    declare @type: KicUnitDataOnDemand: @Configurable;
    
}
