// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.OrganizationType;
import com.innoenergy.kic2.domain.OrganizationTypeDataOnDemand;
import com.innoenergy.kic2.domain.OrganizationTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrganizationTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrganizationTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrganizationTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OrganizationTypeIntegrationTest: @Transactional;
    
    @Autowired
    private OrganizationTypeDataOnDemand OrganizationTypeIntegrationTest.dod;
    
    @Test
    public void OrganizationTypeIntegrationTest.testCountOrganizationTypes() {
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", dod.getRandomOrganizationType());
        long count = OrganizationType.countOrganizationTypes();
        Assert.assertTrue("Counter for 'OrganizationType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrganizationTypeIntegrationTest.testFindOrganizationType() {
        OrganizationType obj = dod.getRandomOrganizationType();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to provide an identifier", id);
        obj = OrganizationType.findOrganizationType(id);
        Assert.assertNotNull("Find method for 'OrganizationType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OrganizationType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrganizationTypeIntegrationTest.testFindAllOrganizationTypes() {
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", dod.getRandomOrganizationType());
        long count = OrganizationType.countOrganizationTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'OrganizationType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OrganizationType> result = OrganizationType.findAllOrganizationTypes();
        Assert.assertNotNull("Find all method for 'OrganizationType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OrganizationType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrganizationTypeIntegrationTest.testFindOrganizationTypeEntries() {
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", dod.getRandomOrganizationType());
        long count = OrganizationType.countOrganizationTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OrganizationType> result = OrganizationType.findOrganizationTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OrganizationType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OrganizationType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrganizationTypeIntegrationTest.testFlush() {
        OrganizationType obj = dod.getRandomOrganizationType();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to provide an identifier", id);
        obj = OrganizationType.findOrganizationType(id);
        Assert.assertNotNull("Find method for 'OrganizationType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrganizationType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'OrganizationType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrganizationTypeIntegrationTest.testMergeUpdate() {
        OrganizationType obj = dod.getRandomOrganizationType();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to provide an identifier", id);
        obj = OrganizationType.findOrganizationType(id);
        boolean modified =  dod.modifyOrganizationType(obj);
        Integer currentVersion = obj.getVersion();
        OrganizationType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'OrganizationType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrganizationTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", dod.getRandomOrganizationType());
        OrganizationType obj = dod.getNewTransientOrganizationType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OrganizationType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'OrganizationType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrganizationTypeIntegrationTest.testRemove() {
        OrganizationType obj = dod.getRandomOrganizationType();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrganizationType' failed to provide an identifier", id);
        obj = OrganizationType.findOrganizationType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'OrganizationType' with identifier '" + id + "'", OrganizationType.findOrganizationType(id));
    }
    
}
