// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.Partner;
import com.innoenergy.kic2.domain.PartnerDataOnDemand;
import com.innoenergy.kic2.domain.PartnerIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PartnerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PartnerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PartnerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PartnerIntegrationTest: @Transactional;
    
    @Autowired
    private PartnerDataOnDemand PartnerIntegrationTest.dod;
    
    @Test
    public void PartnerIntegrationTest.testCountPartners() {
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        long count = Partner.countPartners();
        Assert.assertTrue("Counter for 'Partner' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PartnerIntegrationTest.testFindPartner() {
        Partner obj = dod.getRandomPartner();
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = Partner.findPartner(id);
        Assert.assertNotNull("Find method for 'Partner' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Partner' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PartnerIntegrationTest.testFindAllPartners() {
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        long count = Partner.countPartners();
        Assert.assertTrue("Too expensive to perform a find all test for 'Partner', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Partner> result = Partner.findAllPartners();
        Assert.assertNotNull("Find all method for 'Partner' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Partner' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PartnerIntegrationTest.testFindPartnerEntries() {
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        long count = Partner.countPartners();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Partner> result = Partner.findPartnerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Partner' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Partner' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PartnerIntegrationTest.testFlush() {
        Partner obj = dod.getRandomPartner();
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = Partner.findPartner(id);
        Assert.assertNotNull("Find method for 'Partner' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPartner(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Partner' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartnerIntegrationTest.testMergeUpdate() {
        Partner obj = dod.getRandomPartner();
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = Partner.findPartner(id);
        boolean modified =  dod.modifyPartner(obj);
        Integer currentVersion = obj.getVersion();
        Partner merged = (Partner)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Partner' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartnerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        Partner obj = dod.getNewTransientPartner(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Partner' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Partner' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Partner' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PartnerIntegrationTest.testRemove() {
        Partner obj = dod.getRandomPartner();
        Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = Partner.findPartner(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Partner' with identifier '" + id + "'", Partner.findPartner(id));
    }
    
}
