// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.TradeStyle;
import com.innoenergy.kic2.domain.TradeStyleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TradeStyleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TradeStyleDataOnDemand: @Component;
    
    private Random TradeStyleDataOnDemand.rnd = new SecureRandom();
    
    private List<TradeStyle> TradeStyleDataOnDemand.data;
    
    public TradeStyle TradeStyleDataOnDemand.getNewTransientTradeStyle(int index) {
        TradeStyle obj = new TradeStyle();
        setName(obj, index);
        return obj;
    }
    
    public void TradeStyleDataOnDemand.setName(TradeStyle obj, int index) {
        String name = "name_" + index;
        if (name.length() > 200) {
            name = name.substring(0, 200);
        }
        obj.setName(name);
    }
    
    public TradeStyle TradeStyleDataOnDemand.getSpecificTradeStyle(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TradeStyle obj = data.get(index);
        Long id = obj.getId();
        return TradeStyle.findTradeStyle(id);
    }
    
    public TradeStyle TradeStyleDataOnDemand.getRandomTradeStyle() {
        init();
        TradeStyle obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TradeStyle.findTradeStyle(id);
    }
    
    public boolean TradeStyleDataOnDemand.modifyTradeStyle(TradeStyle obj) {
        return false;
    }
    
    public void TradeStyleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TradeStyle.findTradeStyleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TradeStyle' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TradeStyle>();
        for (int i = 0; i < 10; i++) {
            TradeStyle obj = getNewTransientTradeStyle(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
