// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.innoenergy.kic2.domain;

import com.innoenergy.kic2.domain.TradeStyle;
import com.innoenergy.kic2.domain.TradeStyleDataOnDemand;
import com.innoenergy.kic2.domain.TradeStyleIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TradeStyleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TradeStyleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TradeStyleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TradeStyleIntegrationTest: @Transactional;
    
    @Autowired
    private TradeStyleDataOnDemand TradeStyleIntegrationTest.dod;
    
    @Test
    public void TradeStyleIntegrationTest.testCountTradeStyles() {
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", dod.getRandomTradeStyle());
        long count = TradeStyle.countTradeStyles();
        Assert.assertTrue("Counter for 'TradeStyle' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TradeStyleIntegrationTest.testFindTradeStyle() {
        TradeStyle obj = dod.getRandomTradeStyle();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to provide an identifier", id);
        obj = TradeStyle.findTradeStyle(id);
        Assert.assertNotNull("Find method for 'TradeStyle' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TradeStyle' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TradeStyleIntegrationTest.testFindAllTradeStyles() {
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", dod.getRandomTradeStyle());
        long count = TradeStyle.countTradeStyles();
        Assert.assertTrue("Too expensive to perform a find all test for 'TradeStyle', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TradeStyle> result = TradeStyle.findAllTradeStyles();
        Assert.assertNotNull("Find all method for 'TradeStyle' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TradeStyle' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TradeStyleIntegrationTest.testFindTradeStyleEntries() {
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", dod.getRandomTradeStyle());
        long count = TradeStyle.countTradeStyles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TradeStyle> result = TradeStyle.findTradeStyleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TradeStyle' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TradeStyle' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TradeStyleIntegrationTest.testFlush() {
        TradeStyle obj = dod.getRandomTradeStyle();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to provide an identifier", id);
        obj = TradeStyle.findTradeStyle(id);
        Assert.assertNotNull("Find method for 'TradeStyle' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTradeStyle(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TradeStyle' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TradeStyleIntegrationTest.testMergeUpdate() {
        TradeStyle obj = dod.getRandomTradeStyle();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to provide an identifier", id);
        obj = TradeStyle.findTradeStyle(id);
        boolean modified =  dod.modifyTradeStyle(obj);
        Integer currentVersion = obj.getVersion();
        TradeStyle merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TradeStyle' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TradeStyleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", dod.getRandomTradeStyle());
        TradeStyle obj = dod.getNewTransientTradeStyle(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TradeStyle' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TradeStyle' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TradeStyleIntegrationTest.testRemove() {
        TradeStyle obj = dod.getRandomTradeStyle();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TradeStyle' failed to provide an identifier", id);
        obj = TradeStyle.findTradeStyle(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TradeStyle' with identifier '" + id + "'", TradeStyle.findTradeStyle(id));
    }
    
}
