// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.sts.test3.domain;

import java.util.Set;
import pl.sts.test3.domain.Partner;
import pl.sts.test3.domain.Projekt;

privileged aspect Partner_Roo_JavaBean {
    
    public String Partner.getNazwa() {
        return this.nazwa;
    }
    
    public void Partner.setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    
    public Boolean Partner.getAkcjonariusz() {
        return this.akcjonariusz;
    }
    
    public void Partner.setAkcjonariusz(Boolean akcjonariusz) {
        this.akcjonariusz = akcjonariusz;
    }
    
    public Double Partner.getWartosc() {
        return this.wartosc;
    }
    
    public void Partner.setWartosc(Double wartosc) {
        this.wartosc = wartosc;
    }
    
    public Set<Projekt> Partner.getProjekty() {
        return this.projekty;
    }
    
    public void Partner.setProjekty(Set<Projekt> projekty) {
        this.projekty = projekty;
    }
    
}
