// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.sts.test3.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import pl.sts.test3.domain.Partner;

privileged aspect Partner_Roo_Jpa_Entity {
    
    declare @type: Partner: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Partner.id;
    
    @Version
    @Column(name = "version")
    private Integer Partner.version;
    
    public Long Partner.getId() {
        return this.id;
    }
    
    public void Partner.setId(Long id) {
        this.id = id;
    }
    
    public Integer Partner.getVersion() {
        return this.version;
    }
    
    public void Partner.setVersion(Integer version) {
        this.version = version;
    }
    
}
