// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.sts.test3.domain;

import org.springframework.beans.factory.annotation.Configurable;
import pl.sts.test3.domain.Projekt;

privileged aspect Projekt_Roo_Configurable {
    
    declare @type: Projekt: @Configurable;
    
}
