// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.sts.test3.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import pl.sts.test3.domain.Projekt;

privileged aspect Projekt_Roo_Json {
    
    public String Projekt.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Projekt Projekt.fromJsonToProjekt(String json) {
        return new JSONDeserializer<Projekt>().use(null, Projekt.class).deserialize(json);
    }
    
    public static String Projekt.toJsonArray(Collection<Projekt> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Projekt> Projekt.fromJsonArrayToProjekts(String json) {
        return new JSONDeserializer<List<Projekt>>().use(null, ArrayList.class).use("values", Projekt.class).deserialize(json);
    }
    
}
