// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.sts.test3.domain;

import java.util.Date;
import pl.sts.test3.domain.Partner;
import pl.sts.test3.domain.Projekt;

privileged aspect Projekt_Roo_JavaBean {
    
    public String Projekt.getNazwa() {
        return this.nazwa;
    }
    
    public void Projekt.setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    
    public Date Projekt.getTermin() {
        return this.termin;
    }
    
    public void Projekt.setTermin(Date termin) {
        this.termin = termin;
    }
    
    public Partner Projekt.getPartner() {
        return this.partner;
    }
    
    public void Projekt.setPartner(Partner partner) {
        this.partner = partner;
    }
    
}
